default: &default
  adapter: postgresql
  encoding: unicode

  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME_DEV'] %>

test:
  <<: *default
  database: shopbase_test
  database: <%= ENV['DATABASE_NAME_TEST'] %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
